[package]
name = "giver_prediction"
version = "0.0.1"
published-at = "0x0"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", rev = "devnet" }

[addresses]
giver_prediction = "0x0"
